import Link from "next/link";
import { MoshLogo } from "@/components/logo";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[var(--background)]">
      <nav className="border-b border-[var(--border)] px-6 py-4">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <Link href="/">
            <MoshLogo size="md" />
          </Link>
          <Link href="/" className="text-sm text-[var(--muted-foreground)] hover:text-[var(--foreground)] transition-colors">
            Back to home
          </Link>
        </div>
      </nav>
      <main className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold mb-2">Privacy Policy</h1>
        <p className="text-sm text-[var(--muted-foreground)] mb-10">Last updated: {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</p>

        <div className="space-y-8 text-sm text-[var(--muted-foreground)] leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-[var(--foreground)] mb-3">1. Information We Collect</h2>
            <p>We collect information you provide when creating an account (name, email), task details you submit, and call transcripts generated by our service. We also collect basic usage data such as pages visited and features used.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--foreground)] mb-3">2. How We Use Your Information</h2>
            <p>Your information is used to provide and improve our services, process your tasks, generate call transcripts and summaries, and communicate with you about your account. We do not sell your personal data to third parties.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--foreground)] mb-3">3. Data Storage & Security</h2>
            <p>Your data is stored securely and encrypted in transit. Call recordings and transcripts are stored for your reference and are accessible only to you. We implement industry-standard security measures to protect your information.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--foreground)] mb-3">4. Third-Party Services</h2>
            <p>We use third-party services to provide our functionality, including AI language models for conversation, telephony providers for phone calls, and payment processors for billing. Each operates under their own privacy policies.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--foreground)] mb-3">5. Your Rights</h2>
            <p>You can request access to, correction of, or deletion of your personal data at any time by contacting us at <a href="mailto:hello@mosh.app" className="text-[var(--accent)] hover:underline">hello@mosh.app</a>.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[var(--foreground)] mb-3">6. Contact</h2>
            <p>For questions about this privacy policy, contact us at <a href="mailto:hello@mosh.app" className="text-[var(--accent)] hover:underline">hello@mosh.app</a>.</p>
          </section>
        </div>
      </main>
    </div>
  );
}
